spring.application.name=ecommerce-backend

spring.datasource.url = jdbc:postgresql://localhost:5432/Example
spring.datasource.username = postgres
spring.datasource.password = 1124
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit = false